{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
{{- with .Values.monitoring.serviceMonitor.additionalLabels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $.Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ $.Values.monitoring.serviceMonitor.scrapeTimeout }}
{{- end }}
