apiVersion: v1
kind: ConfigMap
metadata:
  name: mamt2-config
  namespace: {{ .Release.Namespace }}
data:
  USE_REAL_MAMT2: {{ .Values.backend.config.useRealMamt2 | quote }}
  MAMT2_WORKER_URL: {{ .Values.backend.config.workerUrl | quote }}
