apiVersion: v1
kind: Service
metadata:
  name: mamt2-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: mamt2-worker
spec:
  type: {{ .Values.worker.service.type }}

  selector:
    app: mamt2-worker

  ports:
    - name: http
      port: {{ .Values.worker.service.port }}
      targetPort: {{ .Values.worker.service.targetPort }}
      protocol: TCP
